name: 'Rsync Deployments Action'
description: 'GitHub Action for deploying code via rsync over ssh'
author: 'Burnett01'
inputs:
  switches:
    description: 'The switches'
    required: true
  rsh:
    description: 'The remote shell argument'
    required: false
    default: ''
  path:
    description: 'The local path'
    required: false
    default: ''
  upload_path:
    description: 'The remote path'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'send'  
  color: 'gray-dark'
